version: 2.1

parameters:
  run-all:
    type: boolean
    default: false

workflows:
  main:
    when: 
      or: 
        - << pipeline.parameters.run-all >>
    jobs:
      parameters:
        run-all: true
      include:
        ./.circleci/containers/caddy/2.7.6.yml
        ./.circleci/containers/caddy/2.7.4.yml