version: 2.1

parameters:
  run-all:
    type: boolean
    default: false

workflows:
  main:
    when: 
      or: 
        - << pipeline.parameters.run-all >>
    jobs:
      - include:
        ./containers/caddy/2.7.6.yml: run-all
        ./containers/caddy/2.7.6.yml: run-all