---
version: 2

registries:
  dockerhub:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: ${{ github.repository_owner }}
    password: ${{secrets.DOCKER_HUB}}
    replaces-base: true

updates:
  - package-ecosystem: "docker"
    directory: "/imagens"
    registries:
      - dockerhub # Allow version updates for dependencies in this registry
    schedule:
      interval: "daily"
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
