FROM golang:1.25-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o server .

FROM alpine:3.23.2

COPY --from=builder /build/server /server

EXPOSE 8080

ENTRYPOINT ["/server"]
