FROM golang:1.25-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o server .

FROM gcr.io/distroless/static-debian13:nonroot

COPY --from=builder /build/server /server

USER nonroot:nonroot

EXPOSE 8080

ENTRYPOINT ["/server"]
