FROM golang:1.25-alpine AS builder

WORKDIR /build

COPY main.go .

RUN go mod init traefik-http-provider && \
    go get gopkg.in/yaml.v3 && \
    go mod tidy && \
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags="-w -s" -o server .

FROM alpine:3.23.2

COPY --from=builder /build/server /server

EXPOSE 8080

ENTRYPOINT ["/server"]