version: '3'

volumes:
  phpbb-sqlite: {}
  phpbb-files: {}
  phpbb-store: {}
  phpbb-avatars: {}

services:
  phpbb:
    image: igorferreir4/phpbb:3.3.8
    container_name: phpbb
    ports:
      - '8888:80'
    volumes:
      - 'phpbb-sqlite:/phpbb/sqlite'
      - 'phpbb-files:/phpbb/www/files'
      - 'phpbb-store:/phpbb/www/store'
      - 'phpbb-avatars:/phpbb/www/images/avatars/upload'
    environment:
      - PHPBB_INSTALL=true
      - PHPBB_DB_AUTOMIGRATE=true
      - PHPBB_DB_DRIVER=mysqli
      - PHPBB_DB_HOST=db-host
      - PHPBB_DB_PORT=3306
      - PHPBB_DB_NAME=db-name
      - PHPBB_DB_USER=db-user
      - PHPBB_DB_PASSWD=db-user-password