name: 'Use the stock Ubuntu docker.io instead of the default moby-engine'
runs:
  using: 'composite'
  steps:
    - run: |
        set -e
        sudo apt update
        sudo apt remove -y moby-engine moby-containerd moby-runc
        sudo apt install -y docker.io
      shell: bash
