version: 2.1

orbs:
  docker: circleci/docker@2.5.0

parameters:
  build-and-push:
    type: boolean
    default: false
  run-all:
    type: boolean
    default: false

workflows:
  build-amd64:
    environment:
      IMAGE_REPO: igorferreir4/registrator
      IMAGE_TAGS: teste1,123,teste123
    jobs:
      - docker/publish:
          executor:
            image: ubuntu-2204:current
            name: docker/machine
            resource-class: large
          # deploy: false
          step-name: Build and Push
          image: $IMAGE_REPO
          tag: $IMAGE_TAGS
          cache_from: $IMAGE_REPO:IMAGE_TAGS
          update-description: false
          use-buildkit: true 

  build-arm64:
    environment:
      IMAGE_REPO: igorferreir4/registrator
      IMAGE_TAGS: teste4,456,teste456
    jobs:
      - docker/publish:
          executor:
            image: ubuntu-2204:current
            name: docker/machine
            resource-class: large
          # deploy: false
          step-name: Build and Push
          image: $IMAGE_REPO
          tag: $IMAGE_TAGS
          cache_from: $IMAGE_REPO:IMAGE_TAGS
          update-description: false
          use-buildkit: true 


  #  deploy:
  #   executor: docker-docker
  #   steps:
  #     - add_ssh_keys:
  #         fingerprints:
  #           - "SHA256:hLlCCj1OZj3pbBbgrGvfHjdTf20F4IYKyKvyJTMXC/A"
  #     - run:
  #         name: Teste SSH depois da Build
  #         command: |
  #           ssh-keyscan $SSH_HOST_IGOR_ARM >> ~/.ssh/known_hosts
  #           ssh $SSH_USER@$SSH_HOST_IGOR_ARM "echo Executado em "$(date +"%d/%m/%G - %Hh:%Mm:%Ss")" >> circleci.txt" >> ~/circleci.txt"
  #     # - run:
  #     #     name: Teste SSH depois da Build
  #     #     command: |
  #     #       ssh $SSH_USER@$SSH_HOST_IGOR_ARM "~/50GB/docker/executar-docker-compose-up-d.sh >> ~/circleci.txt 2>&1"