version: 2.1

executors:
  docker-machine:
    machine:
      image: ubuntu-2204:2024.01.1
    resource_class: large

parameters:
  build-and-push:
    type: boolean
    default: false
  run-all:
    type: boolean
    default: false

commands:
  setup-qemu-amd64:
    steps:
      - run:
          name: Setup Qemu
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin

  setup-qemu-arm64:
    steps:
      - run:
          name: Setup Qemu
          command: |
            docker run --rm --privileged hectorm/qemu-user-static --reset -p yes
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin

jobs:
   amd64:
    executor: docker-machine
    environment:
      IMAGE_REPO: igorferreir4/registrator
      IMAGE_TAGS: 1.0.1-alpine3.19-amd64
      IMAGE_ARCHS: linux/amd64 #,linux/arm64/v8 #,linux/arm/v6,linux/arm/v7
      CACHE_REPO: igorferreir4/buildcaches
      CACHE_NAME: registrator-1.0.1-alpine3.19-amd64
    working_directory: ~/project/containers/registrator/1.0.1/alpine3.19
    steps:
      - checkout:
          path: ~/project
      - setup-qemu-amd64
      - run:
          name: Build multiarch docker image and push
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled
            BUILDX_ARGS=""
            for tag in $(echo $IMAGE_TAGS | tr "," " "); do
              BUILDX_ARGS="$BUILDX_ARGS -t $IMAGE_REPO:$tag"
            done
            docker buildx build \
            --cache-from=type=registry,ref=$CACHE_REPO:$CACHE_NAME \
            --cache-to=type=registry,ref=$CACHE_REPO:$CACHE_NAME,mode=max \
            --push --platform $IMAGE_ARCHS $BUILDX_ARGS .

   arm64:
    executor: docker-machine
    resource_class: arm.large
    environment:
      IMAGE_REPO: igorferreir4/registrator
      IMAGE_TAGS: 1.0.1-alpine3.19-arm64
      IMAGE_ARCHS: linux/arm64/v8
      CACHE_REPO: igorferreir4/buildcaches
      CACHE_NAME: registrator-1.0.1-alpine3.19-arm64
    working_directory: ~/project/containers/registrator/1.0.1/alpine3.19
    steps:
      - checkout:
          path: ~/project
      - setup-qemu-arm64
      - run:
          name: Build multiarch docker image and push
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled
            BUILDX_ARGS=""
            for tag in $(echo $IMAGE_TAGS | tr "," " "); do
              BUILDX_ARGS="$BUILDX_ARGS -t $IMAGE_REPO:$tag"
            done
            docker buildx build \
            --cache-from=type=registry,ref=$CACHE_REPO:$CACHE_NAME \
            --cache-to=type=registry,ref=$CACHE_REPO:$CACHE_NAME,mode=max \
            --push --platform $IMAGE_ARCHS $BUILDX_ARGS .

   teste-amd64:
    executor: docker-machine
    resource_class: medium
    working_directory: ~/project/containers/registrator/1.0.1/alpine3.19
    steps:
      - checkout:
          path: ~/project
      - run:
          name: docker compose up -d
          command: |
            docker compose -f docker-compose.amd64 pull
            docker compose -f docker-compose.amd64 up -d consul-server
            sleep 10
            docker compose -f docker-compose.amd64 up -d registrator
            sleep 10
            docker logs consul-server
            echo "-----------------------------------------------------------"
            docker logs registrator
      - run:
          name: Check logs
          command: |
            docker logs registrator | awk '/Syncing 27 services on * containers/ { print "EXPRESSÃO ENCONTRADA!"; exit 0 } END { if (NR == 0) print "ERRO, EXPRESSÃO NÃO ENCONTRADA!"; exit 1 }'

   teste-arm64:
    executor: docker-machine
    resource_class: arm.medium
    working_directory: ~/project/containers/registrator/1.0.1/alpine3.19
    steps:
      - checkout:
          path: ~/project
      - run:
          name: docker compose up -d
          command: |
            docker compose -f docker-compose.arm64 pull
            docker compose -f docker-compose.arm64 up -d consul-server
            sleep 10
            docker compose -f docker-compose.arm64 up -d registrator
            sleep 10
            docker logs consul-server
            echo "-----------------------------------------------------------"
            docker logs registrator
      - run:
          name: Check logs
          command: |
            docker logs registrator | awk '/Syncing services on * containers/ { print "EXPRESSÃO ENCONTRADA!"; exit 0 } END { if (NR == 0) print "ERRO, EXPRESSÃO NÃO ENCONTRADA!"; exit 1 }'
      # - run:
      #     name: Check logs
      #     command: |
      #       docker logs registrator | awk '/Syncing services on / { exit 0 }' || exit 1

   deploy:
    executor: docker-machine
    resource_class: medium
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:hLlCCj1OZj3pbBbgrGvfHjdTf20F4IYKyKvyJTMXC/A"
      - run:
          name: Teste SSH depois da Build
          command: |
            ssh $SSH_USER@$SSH_HOST_IGOR_ARM "echo "teste deploy 4" >> ~/circleci.txt"
      # - run:
      #     name: Teste SSH depois da Build
      #     command: |
      #       ssh $SSH_USER@$SSH_HOST_IGOR_ARM "~/50GB/docker/executar-docker-compose-up-d.sh >> ~/circleci.txt 2>&1"

workflows:
   registrator-1-0-1-alpine3-19:
    when: 
      or: 
        - << pipeline.parameters.build-and-push >>
        - << pipeline.parameters.run-all >>
    jobs:
      - amd64
      - arm64
      - teste-amd64:
          requires:
            - amd64
      - teste-arm64:
          requires:
            - arm64
      - deploy:
          requires:
            - teste-amd64
            - teste-arm64