name: Executar Todos

on:
  workflow_dispatch:

jobs:
  aspnet:
    uses: ./.github/workflows/aspnet.yml

  - name: Checkout Repo
    uses: actions/checkout@v3
    with:
      token: ${{ secrets.PAT_TOKEN }}