name: Executar Todos

on:
  workflow_dispatch:

jobs:
  Executando-Todos:
    runs-on: ubuntu-latest
    env:
      NOME: "Executando Todos"
    steps:
      - name: Executando-Todos
        run: echo "::add-mask::$NOME"