name: Build & publish igorferreir4 images

on:
  workflow_dispatch:
  push:
    paths: 
      - 'igorferreir4/**'
      - '!igorferreir4/**/README.md'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./igorferreir4/lighttpd/Dockerfile.edge
            platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
            tags: igorferreir4/lighttpd:edge
          - dockerfile: ./igorferreir4/lighttpd/Dockerfile.stable
            platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
            tags: igorferreir4/lighttpd:1.4.64-r0,igorferreir4/lighttpd:latest
          - dockerfile: ./igorferreir4/phpbb-qemu-arm64/Dockerfile
            platforms: linux/amd64,linux/arm64
            tags: igorferreir4/phpbb-qemu-arm64:3.3.8,igorferreir4/phpbb-qemu-arm64:latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurando QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configurando Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Logando no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.tags }}






# name: Docker Build

# on:
#   push:
#     branches:
#       - 'main'

# jobs:
#   buildx:
#     runs-on: self-hosted
    
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Configurando QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Configurando Buildx
#         id: buildx
#         uses: docker/setup-buildx-action@v2
#         with:
#           version: latest

#       - name: Logando no Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ github.actor }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}   

#       -
#         name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           file: Dockerfile
#           builder: ${{ steps.buildx.outputs.name }}
#           platforms: linux/arm64
#           push: true
#           tags: ${{ github.repository }}:latest
#           cache-from: type=registry,ref=${{ github.repository }}:cache
#           cache-to: type=registry,ref=${{ github.repository }}:cache,mode=max