name: fusionauth-mysql

on:
  workflow_call:
  push:
    paths: 
      - 'imagens/fusionauth-mysql/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./imagens/fusionauth-mysql/1.43.0/Dockerfile
            platforms: linux/amd64,linux/arm64/v8
            tags: igorferreir4/fusionauth-mysql:1.43.0
            cache: type=gha
            nomedocache: fusionauth-mysql
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurando QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configurando Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Logando no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: imagens/fusionauth-mysql/
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.tags }}
          cache-from: ${{ matrix.cache }},scope=build-${{ matrix.nomedocache }}
          cache-to: ${{ matrix.cache }},scope=build-${{ matrix.nomedocache }},mode=max

      - name: Update README.md Docker
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ github.repository_owner }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: igorferreir4/fusionauth-mysql
          readme: imagens/fusionauth-mysql/README.md
          description: FusionAuth App with MySQL JDBC connector